import { describe, it, expect, beforeAll, afterAll } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import { fixturesDir, runSpektaBuild, isRubyAvailable } from "./helpers.js";

const rubyAvailable = isRubyAvailable();

describe("spekta build", () => {
  const projectDir = fixturesDir();
  const webDir = path.join(projectDir, ".spekta/web");
  const mdDir = path.join(projectDir, ".spekta/markdown");

  beforeAll(() => {
    // Clean previous output
    fs.rmSync(path.join(projectDir, ".spekta"), { recursive: true, force: true });
    if (rubyAvailable) {
      runSpektaBuild(projectDir);
    }
  });

  afterAll(() => {
    fs.rmSync(path.join(projectDir, ".spekta"), { recursive: true, force: true });
  });

  describe.runIf(rubyAvailable)("Web レンダラー", () => {
    it("ページごとの HTML ファイルが生成される", () => {
      const pages = fs.readdirSync(webDir).filter(e =>
        fs.statSync(path.join(webDir, e)).isDirectory() && e !== "images"
      );
      expect(pages.length).toBeGreaterThan(0);
      for (const page of pages) {
        expect(fs.existsSync(path.join(webDir, page, "index.html"))).toBe(true);
      }
    });

    it("index.html が最初のページにリダイレクトする", () => {
      const html = fs.readFileSync(path.join(webDir, "index.html"), "utf-8");
      expect(html).toContain("http-equiv=\"refresh\"");
    });

    it("404.html がルートにリダイレクトする", () => {
      const html = fs.readFileSync(path.join(webDir, "404.html"), "utf-8");
      expect(html).toContain("url=/");
    });

    it("HTML にページタイトルが含まれる", () => {
      const pages = fs.readdirSync(webDir).filter(e =>
        fs.statSync(path.join(webDir, e)).isDirectory() && e !== "images"
      );
      const html = fs.readFileSync(path.join(webDir, pages[0], "index.html"), "utf-8");
      expect(html).toContain("spec-content__title");
    });

    it("HTML にサイドバーが含まれる", () => {
      const pages = fs.readdirSync(webDir).filter(e =>
        fs.statSync(path.join(webDir, e)).isDirectory() && e !== "images"
      );
      const html = fs.readFileSync(path.join(webDir, pages[0], "index.html"), "utf-8");
      expect(html).toContain("sidebar");
    });

    it("HTML にステップが自然言語で表示される", () => {
      const pages = fs.readdirSync(webDir).filter(e =>
        fs.statSync(path.join(webDir, e)).isDirectory() && e !== "images"
      );
      const html = fs.readFileSync(path.join(webDir, pages[0], "index.html"), "utf-8");
      expect(html).toContain("ページを開く");
    });

    it("HTML にヘッダーのプロダクト名が含まれる", () => {
      const pages = fs.readdirSync(webDir).filter(e =>
        fs.statSync(path.join(webDir, e)).isDirectory() && e !== "images"
      );
      const html = fs.readFileSync(path.join(webDir, pages[0], "index.html"), "utf-8");
      expect(html).toContain("テストプロダクト");
    });

    it("HTML にフッターが含まれる", () => {
      const pages = fs.readdirSync(webDir).filter(e =>
        fs.statSync(path.join(webDir, e)).isDirectory() && e !== "images"
      );
      const html = fs.readFileSync(path.join(webDir, pages[0], "index.html"), "utf-8");
      expect(html).toContain("Generated by Spekta");
    });

    it("HTML に see 参照がリンクとして含まれる", () => {
      const pages = fs.readdirSync(webDir).filter(e =>
        fs.statSync(path.join(webDir, e)).isDirectory() && e !== "images"
      );
      const html = fs.readFileSync(path.join(webDir, pages[0], "index.html"), "utf-8");
      expect(html).toContain("spec-content__related-link");
    });

    it("HTML に why 属性がコールアウトとして含まれる", () => {
      const pages = fs.readdirSync(webDir).filter(e =>
        fs.statSync(path.join(webDir, e)).isDirectory() && e !== "images"
      );
      let found = false;
      for (const page of pages) {
        const html = fs.readFileSync(path.join(webDir, page, "index.html"), "utf-8");
        if (html.includes("callout--why")) {
          found = true;
          break;
        }
      }
      expect(found).toBe(true);
    });
  });

  describe.runIf(rubyAvailable)("Markdown レンダラー", () => {
    it("ページごとの .md ファイルが生成される", () => {
      const files = fs.readdirSync(mdDir).filter(f => f.endsWith(".md"));
      expect(files.length).toBeGreaterThan(0);
    });

    it("Markdown にページタイトルが h1 として含まれる", () => {
      const files = fs.readdirSync(mdDir).filter(f => f.endsWith(".md"));
      const md = fs.readFileSync(path.join(mdDir, files[0]), "utf-8");
      expect(md).toMatch(/^# .+/m);
    });

    it("Markdown にステップが番号付きリストとして含まれる", () => {
      const files = fs.readdirSync(mdDir).filter(f => f.endsWith(".md"));
      const md = fs.readFileSync(path.join(mdDir, files[0]), "utf-8");
      expect(md).toContain("1. ページを開く");
    });

    it("Markdown に see 参照がリンクとして含まれる", () => {
      const files = fs.readdirSync(mdDir).filter(f => f.endsWith(".md"));
      let found = false;
      for (const file of files) {
        const md = fs.readFileSync(path.join(mdDir, file), "utf-8");
        if (md.match(/\[.+\]\(.+\.md\)/)) { found = true; break; }
      }
      expect(found).toBe(true);
    });
  });
});
