import { describe, it, expect, beforeAll, afterAll } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import {
  rspecFixturesDir, vitestFixturesDir, runSpektaBuild, isRubyAvailable,
  getGeneratedPages, readPageHtml,
} from "./helpers.js";

const rubyAvailable = isRubyAvailable();
const context = describe;

// [spekta:summary] テストコードを解析し、Web/Markdown 形式の仕様書を生成するコマンド。
describe("spekta build", () => {

  context.runIf(rubyAvailable)("RSpec の Feature spec から仕様書を生成する場合", () => {
    const projectDir = rspecFixturesDir();
    const webDir = path.join(projectDir, ".spekta/web");
    const mdDir = path.join(projectDir, ".spekta/markdown");

    beforeAll(() => {
      fs.rmSync(path.join(projectDir, ".spekta"), { recursive: true, force: true });
      runSpektaBuild(projectDir);
    });

    afterAll(() => {
      fs.rmSync(path.join(projectDir, ".spekta"), { recursive: true, force: true });
    });

    context("Web レンダラーの場合", () => {
      it("ページごとの HTML ファイルが生成されること", () => {
        // [spekta:step] spekta build を実行する
        // [spekta:step] .spekta/web/ 配下にページディレクトリが存在する
        // [spekta:step] 各ページに index.html が含まれる
        const pages = getGeneratedPages(webDir);
        expect(pages.length).toBeGreaterThan(0);
        for (const page of pages) {
          expect(fs.existsSync(path.join(webDir, page, "index.html"))).toBe(true);
        }
      });

      it("index.html が最初のページにリダイレクトすること", () => {
        // [spekta:step] ルートの index.html を読み込む
        const html = fs.readFileSync(path.join(webDir, "index.html"), "utf-8");
        // [spekta:step] meta refresh によるリダイレクトが設定されている
        expect(html).toContain("http-equiv=\"refresh\"");
      });

      it("404.html がルートにリダイレクトすること", () => {
        // [spekta:step] 404.html を読み込む
        const html = fs.readFileSync(path.join(webDir, "404.html"), "utf-8");
        // [spekta:step] ルートへのリダイレクトが設定されている
        expect(html).toContain("url=/");
      });

      it("HTML にページタイトルが含まれること", () => {
        // [spekta:step] 生成された HTML を読み込む
        const pages = getGeneratedPages(webDir);
        const html = readPageHtml(webDir, pages[0]);
        // [spekta:step] タイトル要素が存在する
        expect(html).toContain("spec-content__title");
      });

      it("HTML にサイドバーが含まれること", () => {
        // [spekta:step] 生成された HTML を読み込む
        const pages = getGeneratedPages(webDir);
        const html = readPageHtml(webDir, pages[0]);
        // [spekta:step] サイドバー要素が存在する
        expect(html).toContain("sidebar");
      });

      it("HTML にヘッダーのプロダクト名が含まれること", () => {
        // [spekta:step] 生成された HTML を読み込む
        const pages = getGeneratedPages(webDir);
        const html = readPageHtml(webDir, pages[0]);
        // [spekta:step] .spekta.yml の name が表示されている
        expect(html).toContain("テストプロダクト");
      });

      it("HTML にフッターが含まれること", () => {
        // [spekta:step] 生成された HTML を読み込む
        const pages = getGeneratedPages(webDir);
        const html = readPageHtml(webDir, pages[0]);
        // [spekta:step] フッターに "Generated by Spekta" が含まれる
        expect(html).toContain("Generated by Spekta");
      });

      it("HTML にステップが自然言語で表示されること", () => {
        // [spekta:step] 全ページの HTML を走査する
        const pages = getGeneratedPages(webDir);
        let found = false;
        for (const page of pages) {
          if (readPageHtml(webDir, page).includes("ページを開く")) { found = true; break; }
        }
        // [spekta:step] Capybara の visit が「ページを開く」に変換されている
        expect(found).toBe(true);
      });

      it("HTML に see 参照がリンクとして含まれること", () => {
        // [spekta:step] 全ページの HTML を走査する
        const pages = getGeneratedPages(webDir);
        let found = false;
        for (const page of pages) {
          if (readPageHtml(webDir, page).includes("spec-content__related-link")) { found = true; break; }
        }
        // [spekta:step] [spekta:see] がリンク要素として出力されている
        expect(found).toBe(true);
      });

      it("HTML に summary 属性が含まれること", () => {
        // [spekta:step] 全ページの HTML を走査する
        const pages = getGeneratedPages(webDir);
        let found = false;
        for (const page of pages) {
          if (readPageHtml(webDir, page).includes("spec-content__summary")) { found = true; break; }
        }
        // [spekta:step] [spekta:summary] が要約要素として出力されている
        expect(found).toBe(true);
      });

      it("HTML に why 属性がコールアウトとして含まれること", () => {
        // [spekta:step] 全ページの HTML を走査する
        const pages = getGeneratedPages(webDir);
        let found = false;
        for (const page of pages) {
          if (readPageHtml(webDir, page).includes("callout--why")) { found = true; break; }
        }
        // [spekta:step] [spekta:why] がコールアウト要素として出力されている
        expect(found).toBe(true);
      });
    });

    context("Markdown レンダラーの場合", () => {
      it("ページごとの .md ファイルが生成されること", () => {
        // [spekta:step] .spekta/markdown/ 配下のファイルを確認する
        const files = fs.readdirSync(mdDir).filter((f: string) => f.endsWith(".md"));
        // [spekta:step] .md ファイルが 1 つ以上存在する
        expect(files.length).toBeGreaterThan(0);
      });

      it("Markdown にページタイトルが h1 として含まれること", () => {
        // [spekta:step] 生成された Markdown を読み込む
        const files = fs.readdirSync(mdDir).filter((f: string) => f.endsWith(".md"));
        const md = fs.readFileSync(path.join(mdDir, files[0]), "utf-8");
        // [spekta:step] h1 見出し（# ...）が存在する
        expect(md).toMatch(/^# .+/m);
      });

      it("Markdown にステップが番号付きリストとして含まれること", () => {
        // [spekta:step] 全 Markdown ファイルを走査する
        const files = fs.readdirSync(mdDir).filter((f: string) => f.endsWith(".md"));
        let found = false;
        for (const file of files) {
          const md = fs.readFileSync(path.join(mdDir, file), "utf-8");
          if (md.includes("1. ページを開く")) { found = true; break; }
        }
        // [spekta:step] Capybara の visit が「1. ページを開く」として出力されている
        expect(found).toBe(true);
      });

      it("Markdown に see 参照がリンクとして含まれること", () => {
        // [spekta:step] 全 Markdown ファイルを走査する
        const files = fs.readdirSync(mdDir).filter((f: string) => f.endsWith(".md"));
        let found = false;
        for (const file of files) {
          const md = fs.readFileSync(path.join(mdDir, file), "utf-8");
          if (md.match(/\[.+\]\(.+\.md\)/)) { found = true; break; }
        }
        // [spekta:step] [spekta:see] が Markdown リンクとして出力されている
        expect(found).toBe(true);
      });
    });
  });

  context("Vitest のテストから仕様書を生成する場合", () => {
    const projectDir = vitestFixturesDir();
    const webDir = path.join(projectDir, ".spekta/web");
    const mdDir = path.join(projectDir, ".spekta/markdown");

    beforeAll(() => {
      fs.rmSync(path.join(projectDir, ".spekta"), { recursive: true, force: true });
      runSpektaBuild(projectDir);
    });

    afterAll(() => {
      fs.rmSync(path.join(projectDir, ".spekta"), { recursive: true, force: true });
    });

    context("Web レンダラーの場合", () => {
      it("ページごとの HTML ファイルが生成されること", () => {
        // [spekta:step] spekta build を実行する
        // [spekta:step] .spekta/web/ 配下にページディレクトリが存在する
        // [spekta:step] 各ページに index.html が含まれる
        const pages = getGeneratedPages(webDir);
        expect(pages.length).toBeGreaterThan(0);
        for (const page of pages) {
          expect(fs.existsSync(path.join(webDir, page, "index.html"))).toBe(true);
        }
      });

      it("index.html が最初のページにリダイレクトすること", () => {
        // [spekta:step] ルートの index.html を読み込む
        const html = fs.readFileSync(path.join(webDir, "index.html"), "utf-8");
        // [spekta:step] meta refresh によるリダイレクトが設定されている
        expect(html).toContain("http-equiv=\"refresh\"");
      });

      it("404.html がルートにリダイレクトすること", () => {
        // [spekta:step] 404.html を読み込む
        const html = fs.readFileSync(path.join(webDir, "404.html"), "utf-8");
        // [spekta:step] ルートへのリダイレクトが設定されている
        expect(html).toContain("url=/");
      });

      it("HTML にページタイトルが含まれること", () => {
        // [spekta:step] 生成された HTML を読み込む
        const pages = getGeneratedPages(webDir);
        const html = readPageHtml(webDir, pages[0]);
        // [spekta:step] タイトル要素が存在する
        expect(html).toContain("spec-content__title");
      });

      it("HTML にサイドバーが含まれること", () => {
        // [spekta:step] 生成された HTML を読み込む
        const pages = getGeneratedPages(webDir);
        const html = readPageHtml(webDir, pages[0]);
        // [spekta:step] サイドバー要素が存在する
        expect(html).toContain("sidebar");
      });

      it("HTML にヘッダーのプロダクト名が含まれること", () => {
        // [spekta:step] 生成された HTML を読み込む
        const pages = getGeneratedPages(webDir);
        const html = readPageHtml(webDir, pages[0]);
        // [spekta:step] .spekta.yml の name が表示されている
        expect(html).toContain("テストプロダクト");
      });

      it("HTML にフッターが含まれること", () => {
        // [spekta:step] 生成された HTML を読み込む
        const pages = getGeneratedPages(webDir);
        const html = readPageHtml(webDir, pages[0]);
        // [spekta:step] フッターに "Generated by Spekta" が含まれる
        expect(html).toContain("Generated by Spekta");
      });

      it("HTML に summary 属性が含まれること", () => {
        // [spekta:step] 全ページの HTML を走査する
        const pages = getGeneratedPages(webDir);
        let found = false;
        for (const page of pages) {
          if (readPageHtml(webDir, page).includes("spec-content__summary")) { found = true; break; }
        }
        // [spekta:step] [spekta:summary] が要約要素として出力されている
        expect(found).toBe(true);
      });

      it("HTML に why 属性がコールアウトとして含まれること", () => {
        // [spekta:step] 全ページの HTML を走査する
        const pages = getGeneratedPages(webDir);
        let found = false;
        for (const page of pages) {
          if (readPageHtml(webDir, page).includes("callout--why")) { found = true; break; }
        }
        // [spekta:step] [spekta:why] がコールアウト要素として出力されている
        expect(found).toBe(true);
      });

      it("HTML に [spekta:step] コメントがステップとして含まれること", () => {
        // [spekta:step] 全ページの HTML を走査する
        const pages = getGeneratedPages(webDir);
        let found = false;
        for (const page of pages) {
          if (readPageHtml(webDir, page).includes("検索画面を開く")) { found = true; break; }
        }
        // [spekta:step] [spekta:step] のテキストがステップとして出力されている
        expect(found).toBe(true);
      });
    });

    context("Markdown レンダラーの場合", () => {
      it("ページごとの .md ファイルが生成されること", () => {
        // [spekta:step] .spekta/markdown/ 配下のファイルを確認する
        const files = fs.readdirSync(mdDir).filter((f: string) => f.endsWith(".md"));
        // [spekta:step] .md ファイルが 1 つ以上存在する
        expect(files.length).toBeGreaterThan(0);
      });

      it("Markdown にページタイトルが h1 として含まれること", () => {
        // [spekta:step] 生成された Markdown を読み込む
        const files = fs.readdirSync(mdDir).filter((f: string) => f.endsWith(".md"));
        const md = fs.readFileSync(path.join(mdDir, files[0]), "utf-8");
        // [spekta:step] h1 見出し（# ...）が存在する
        expect(md).toMatch(/^# .+/m);
      });

      it("Markdown に [spekta:step] コメントが番号付きリストとして含まれること", () => {
        // [spekta:step] 全 Markdown ファイルを走査する
        const files = fs.readdirSync(mdDir).filter((f: string) => f.endsWith(".md"));
        let found = false;
        for (const file of files) {
          const md = fs.readFileSync(path.join(mdDir, file), "utf-8");
          if (md.includes("1. 検索画面を開く")) { found = true; break; }
        }
        // [spekta:step] [spekta:step] のテキストが番号付きリストとして出力されている
        expect(found).toBe(true);
      });
    });
  });
});
