import { describe, it, expect, beforeAll, afterAll } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import {
  rspecFixturesDir, vitestFixturesDir, runSpektaBuild, isRubyAvailable,
  getGeneratedPages, readPageHtml,
} from "./helpers.js";

const rubyAvailable = isRubyAvailable();

/**
 * 共通の出力検証。アナライザーに依存しない。
 */
function verifyWebOutput(webDir: string) {
  it("ページごとの HTML ファイルが生成される", () => {
    const pages = getGeneratedPages(webDir);
    expect(pages.length).toBeGreaterThan(0);
    for (const page of pages) {
      expect(fs.existsSync(path.join(webDir, page, "index.html"))).toBe(true);
    }
  });

  it("index.html が最初のページにリダイレクトする", () => {
    const html = fs.readFileSync(path.join(webDir, "index.html"), "utf-8");
    expect(html).toContain("http-equiv=\"refresh\"");
  });

  it("404.html がルートにリダイレクトする", () => {
    const html = fs.readFileSync(path.join(webDir, "404.html"), "utf-8");
    expect(html).toContain("url=/");
  });

  it("HTML にページタイトルが含まれる", () => {
    const pages = getGeneratedPages(webDir);
    const html = readPageHtml(webDir, pages[0]);
    expect(html).toContain("spec-content__title");
  });

  it("HTML にサイドバーが含まれる", () => {
    const pages = getGeneratedPages(webDir);
    const html = readPageHtml(webDir, pages[0]);
    expect(html).toContain("sidebar");
  });

  it("HTML にヘッダーのプロダクト名が含まれる", () => {
    const pages = getGeneratedPages(webDir);
    const html = readPageHtml(webDir, pages[0]);
    expect(html).toContain("テストプロダクト");
  });

  it("HTML にフッターが含まれる", () => {
    const pages = getGeneratedPages(webDir);
    const html = readPageHtml(webDir, pages[0]);
    expect(html).toContain("Generated by Spekta");
  });

  it("HTML に summary 属性が含まれる", () => {
    const pages = getGeneratedPages(webDir);
    let found = false;
    for (const page of pages) {
      if (readPageHtml(webDir, page).includes("spec-content__summary")) { found = true; break; }
    }
    expect(found).toBe(true);
  });

  it("HTML に why 属性がコールアウトとして含まれる", () => {
    const pages = getGeneratedPages(webDir);
    let found = false;
    for (const page of pages) {
      if (readPageHtml(webDir, page).includes("callout--why")) { found = true; break; }
    }
    expect(found).toBe(true);
  });
}

function verifyMarkdownOutput(mdDir: string) {
  it("ページごとの .md ファイルが生成される", () => {
    const files = fs.readdirSync(mdDir).filter(f => f.endsWith(".md"));
    expect(files.length).toBeGreaterThan(0);
  });

  it("Markdown にページタイトルが h1 として含まれる", () => {
    const files = fs.readdirSync(mdDir).filter(f => f.endsWith(".md"));
    const md = fs.readFileSync(path.join(mdDir, files[0]), "utf-8");
    expect(md).toMatch(/^# .+/m);
  });
}

describe("spekta build", () => {
  describe.runIf(rubyAvailable)("RSpec の Feature spec から仕様書を生成できる", () => {
    const projectDir = rspecFixturesDir();
    const webDir = path.join(projectDir, ".spekta/web");
    const mdDir = path.join(projectDir, ".spekta/markdown");

    beforeAll(() => {
      fs.rmSync(path.join(projectDir, ".spekta"), { recursive: true, force: true });
      runSpektaBuild(projectDir);
    });

    afterAll(() => {
      fs.rmSync(path.join(projectDir, ".spekta"), { recursive: true, force: true });
    });

    describe("Web レンダラー", () => {
      verifyWebOutput(webDir);

      it("HTML にステップが自然言語で表示される", () => {
        const pages = getGeneratedPages(webDir);
        let found = false;
        for (const page of pages) {
          if (readPageHtml(webDir, page).includes("ページを開く")) { found = true; break; }
        }
        expect(found).toBe(true);
      });

      it("HTML に see 参照がリンクとして含まれる", () => {
        const pages = getGeneratedPages(webDir);
        let found = false;
        for (const page of pages) {
          if (readPageHtml(webDir, page).includes("spec-content__related-link")) { found = true; break; }
        }
        expect(found).toBe(true);
      });
    });

    describe("Markdown レンダラー", () => {
      verifyMarkdownOutput(mdDir);

      it("Markdown にステップが番号付きリストとして含まれる", () => {
        const files = fs.readdirSync(mdDir).filter(f => f.endsWith(".md"));
        let found = false;
        for (const file of files) {
          const md = fs.readFileSync(path.join(mdDir, file), "utf-8");
          if (md.includes("1. ページを開く")) { found = true; break; }
        }
        expect(found).toBe(true);
      });

      it("Markdown に see 参照がリンクとして含まれる", () => {
        const files = fs.readdirSync(mdDir).filter(f => f.endsWith(".md"));
        let found = false;
        for (const file of files) {
          const md = fs.readFileSync(path.join(mdDir, file), "utf-8");
          if (md.match(/\[.+\]\(.+\.md\)/)) { found = true; break; }
        }
        expect(found).toBe(true);
      });
    });
  });

  describe("Vitest のテストから仕様書を生成できる", () => {
    const projectDir = vitestFixturesDir();
    const webDir = path.join(projectDir, ".spekta/web");
    const mdDir = path.join(projectDir, ".spekta/markdown");

    beforeAll(() => {
      fs.rmSync(path.join(projectDir, ".spekta"), { recursive: true, force: true });
      runSpektaBuild(projectDir);
    });

    afterAll(() => {
      fs.rmSync(path.join(projectDir, ".spekta"), { recursive: true, force: true });
    });

    describe("Web レンダラー", () => {
      verifyWebOutput(webDir);
    });

    describe("Markdown レンダラー", () => {
      verifyMarkdownOutput(mdDir);
    });
  });
});
